# Generated by Django 5.0.3 on 2024-03-15 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата производства продукта'),
        ),
    ]
